dist: xenial
language: python
python: 
  - 3.7
install:
  - pip install python-dateutil pytest kodi-addon-checker
script:
  - py.test -v
  - unzip *.zip -d script.tubecast
  - kodi-addon-checker --branch=krypton script.tubecast
before_script:
  - pip install git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -z script.tubecast # Create an installable ZIP
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  # Publish an installable ZIP to GitHub Releases
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the official Kodi repository
  - provider: script
    script: submit-addon -r repo-scripts -b krypton --pull-request script.tubecast
    on:
      tags: true
notifications:
  email: true