language: python
matrix:
  include:
    - python: "2.7"
  allow_failures:
    - python: "2.6"
    - python: "3.5"
    - python: "nightly"
# command to install dependencies
install: 
  - pip install python-dateutil pytest
# command to run tests
script: py.test -v
before_deploy:
  - pip install kodi-addon-checker
  - pip install git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -z script.tubecast # Create an installable ZIP
  - export RELEASE_ZIP=$(ls *.zip)
addon_check:
  - provider: script
    script: kodi-addon-checker --branch=krypton .
    on:
      tags: false
deploy:
  # Publish an installable ZIP to GitHub Releases
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the official Kodi repository
  - provider: script
    script: submit-addon -r repo-scripts -b krypton --pull-request script.tubecast
    on:
      tags: true
notifications:
  email: true